server:
  port: 9999

spring:
  application:
    name: StudentProject

  datasource:
    url: jdbc:mysql://localhost:3306/studentproject
    username: root
    password: 2007
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 60000
